force-app/main/default/objects/Doctor_Appointment__c/Doctor_Appointment__c.object-meta.xml
<CustomObject>
    <label>Doctor Appointment</label>
    <nameField>
        <displayFormat>DA-{0000}</displayFormat>
        <label>Doctor Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctor Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor_Appointment__c/fields/Eyeground_Investigation__c.field-meta.xml
<CustomField>
    <fullName>Eyeground_Investigation__c</fullName>
    <label>Eyeground Investigation</label>
    <referenceTo>Eyeground_Investigation__c</referenceTo>
    <relationshipLabel>Doctor Appointments</relationshipLabel>
    <relationshipName>Doctor_Appointments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor_Appointment__c/fields/Objective_status__c.field-meta.xml
<CustomField>
    <fullName>Objective_status__c</fullName>
    <inlineHelpText>Объективный статус</inlineHelpText>
    <label>Objective status</label>
    <referenceTo>Objective_status__c</referenceTo>
    <relationshipLabel>Doctor Appointments</relationshipLabel>
    <relationshipName>Doctor_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eyeground_Investigation__c/Eyeground_Investigation__c.object-meta.xml
<CustomObject>
    <label>Eyeground Investigation</label>
    <nameField>
        <displayFormat>EI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eyeground Investigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective_status__c/Objective_status__c.object-meta.xml
<CustomObject>
    <label>Objective status</label>
    <nameField>
        <displayFormat>OS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objective statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DoctorAppointmentController.cls
public with sharing class DoctorAppointmentController {
    private static final Map<String, SObjectType> SOBJECT_TYPE_MAP = Schema.getGlobalDescribe();

    @AuraEnabled
    public static LightningResponse createRecord(String data) {
        LightningResponse response = new LightningResponse();
        Map<String, String> resultMap = new Map<String, String>();
        try {
            Map<String, Object> inputData = (Map<String, Object>) JSON.deserializeUntyped(data);
            SObject objStatus;
            SObject eyeGround;
            if (inputData.get('objectiveStatus') != null) {
                objStatus = createSObject((Map<String, Object>) inputData.get('objectiveStatus'), 'Objective_status__c');
            }
            if (objStatus == null) objStatus = new Objective_status__c();
            upsert objStatus;
            resultMap.put('objStatus', objStatus.Id);

            if (inputData.get('eyeground') != null) {
                eyeGround = createSObject((Map<String, Object>) inputData.get('eyeground'), 'Eyeground_Investigation__c');
            }
            if (eyeGround == null) eyeGround = new Eyeground_Investigation__c();
            upsert eyeGround;
            resultMap.put('eyeGround', eyeGround.Id);
            System.debug('appointment >>>>>>>>>>>>>>>>> ');
            SObject doctorApp = createSObject((Map<String, Object>) inputData.get('doctorAppointment'), 'Doctor_Appointment__c');
            if (doctorApp.Id == null) {
                doctorApp.put('Objective_status__c', objStatus.get('id'));
                doctorApp.put('Eyeground_Investigation__c', eyeGround.get('id'));
            }
            System.debug(JSON.serializePretty(doctorApp));
            upsert doctorApp;
            resultMap.put('appointmentId', doctorApp.Id);
            response.setBody(resultMap).setSuccess(true);
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            response.setError(e.getMessage());
        }
        return response;
    }

    private static SObject createSObject(Map<String, Object> od, String sobjectApiName) {
        System.debug('od ' + od);
        SObject newSObject;
        if (SOBJECT_TYPE_MAP.get(sobjectApiName) != null) {
            newSObject = SOBJECT_TYPE_MAP.get(sobjectApiName).newSObject();
            if (od != null && od.size() > 0) {
                Map<String, SObjectField> fieldsMap = SOBJECT_TYPE_MAP.get(sobjectApiName).getDescribe().fields.getMap();
                for (String field : fieldsMap.keySet()) {
                    if (field == 'objective_status__c' || field == 'eyeground_investigation__c') {
                        continue;
                    }
                    Object value = od.get(field);
                    System.debug('field ' + field);
                    System.debug('value ' + value);
                    if (value != null) {
                        try {
                            switch on fieldsMap.get(field).getDescribe().getType() {
                                when DATE {
                                    value = Date.parse((String) value);
                                }
                                when DOUBLE {
                                    value = Double.valueOf(value);
                                }
                                when INTEGER {
                                    value = Integer.valueOf(value);
                                }
                                when BOOLEAN {
                                    value = Boolean.valueOf(value);
                                }
                            }
                            newSObject.put(field, value);
                        } catch (Exception exc) {
                            System.debug('Casting data exception : ' + exc.getMessage() + '\n' + exc.getStackTraceString());
                        }
                    }
                }
            }
            return newSObject;
        } else {
            throw new DoctorAppointmentException('No such Sobject or it doesn\'t accessible - Objective_status__c ');
        }
    }

    private class DoctorAppointmentException extends Exception{}

}