force-app/main/default/objects/Objective_status__c/Objective_status__c.object-meta.xml
<CustomObject>
    <label>Objective status</label>
    <nameField>
        <displayFormat>OS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objective statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective_status__c/fields/Anterior_Chamber_Angle_Left__c.field-meta.xml
<CustomField>
    <fullName>Anterior_Chamber_Angle_Left__c</fullName>
    <inlineHelpText>Угол передней камеры левый глаз</inlineHelpText>
    <label>Anterior Chamber Angle Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Anterior_Chamber_Angle_Right__c.field-meta.xml
<CustomField>
    <fullName>Anterior_Chamber_Angle_Right__c</fullName>
    <inlineHelpText>Угол передней камеры правый глаз</inlineHelpText>
    <label>Anterior Chamber Angle Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Anterior_Chamber_Left__c.field-meta.xml
<CustomField>
    <fullName>Anterior_Chamber_Left__c</fullName>
    <inlineHelpText>Передняя камера статус</inlineHelpText>
    <label>Anterior Chamber Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Anterior_Chamber_Right__c.field-meta.xml
<CustomField>
    <fullName>Anterior_Chamber_Right__c</fullName>
    <inlineHelpText>Передняя камера</inlineHelpText>
    <label>Anterior Chamber Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Anterior_Posterior_Axis_Left__c.field-meta.xml
<CustomField>
    <fullName>Anterior_Posterior_Axis_Left__c</fullName>
    <inlineHelpText>Передне-задняя ось. Пример: 22,88 мм</inlineHelpText>
    <label>Anterior Posterior Axis Left</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Anterior_Posterior_Axis_Right__c.field-meta.xml
<CustomField>
    <fullName>Anterior_Posterior_Axis_Right__c</fullName>
    <inlineHelpText>Передне-задняя ось правый глаз. Пример</inlineHelpText>
    <label>Anterior Posterior Axis Right</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Axys_Left_Cor__c.field-meta.xml
<CustomField>
    <fullName>Axys_Left_Cor__c</fullName>
    <inlineHelpText>Значение оси с коррекцией, левый глаз. Пример: 180</inlineHelpText>
    <label>Axys Left (Cor)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Axys_Right_Cor__c.field-meta.xml
<CustomField>
    <fullName>Axys_Right_Cor__c</fullName>
    <inlineHelpText>Значение оси с коррекцией, правый глаз. Пример: 180</inlineHelpText>
    <label>Axys Right (Cor)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Central_Corneal_Thickness_Left__c.field-meta.xml
<CustomField>
    <fullName>Central_Corneal_Thickness_Left__c</fullName>
    <inlineHelpText>Центральная толщина роговицы левый глаз. Пример: 525 мкм</inlineHelpText>
    <label>Central Corneal Thickness Left</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Central_Corneal_Thickness_Right__c.field-meta.xml
<CustomField>
    <fullName>Central_Corneal_Thickness_Right__c</fullName>
    <inlineHelpText>Центральная толщина роговицы правый глаз. Пример: 525 мкм</inlineHelpText>
    <label>Central Corneal Thickness Right</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Conjunctiva_Left__c.field-meta.xml
<CustomField>
    <fullName>Conjunctiva_Left__c</fullName>
    <description>{Id;Id}</description>
    <inlineHelpText>Конъюнктива плевого глаза - статус</inlineHelpText>
    <label>Conjunctiva Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Conjunctiva_Right__c.field-meta.xml
<CustomField>
    <fullName>Conjunctiva_Right__c</fullName>
    <description>{Id;Id}</description>
    <inlineHelpText>Конъюнктива правгого глаза - статус</inlineHelpText>
    <label>Conjunctiva Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Cornea_Left__c.field-meta.xml
<CustomField>
    <fullName>Cornea_Left__c</fullName>
    <description>{Id%description;Id%description}</description>
    <inlineHelpText>Роговица левого глаза - статус</inlineHelpText>
    <label>Cornea Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Cornea_Right__c.field-meta.xml
<CustomField>
    <fullName>Cornea_Right__c</fullName>
    <description>{Id%description;Id%description}</description>
    <inlineHelpText>Роговица правого глаза - статус</inlineHelpText>
    <label>Cornea Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Cylinder_Left_Cor__c.field-meta.xml
<CustomField>
    <fullName>Cylinder_Left_Cor__c</fullName>
    <inlineHelpText>Значение цилиндра с коррекцией, левый глаз. Пример: +1,25</inlineHelpText>
    <label>Cylinder Left (Cor)</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Cylinder_Right_Cor__c.field-meta.xml
<CustomField>
    <fullName>Cylinder_Right_Cor__c</fullName>
    <inlineHelpText>Значение цилиндра с коррекцией, правый глаз. Пример: +1,25</inlineHelpText>
    <label>Cylinder Right (Cor)</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eye_Lens_Left__c.field-meta.xml
<CustomField>
    <fullName>Eye_Lens_Left__c</fullName>
    <inlineHelpText>Хрусталик левого глаза</inlineHelpText>
    <label>Eye Lens Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eye_Lens_Right__c.field-meta.xml
<CustomField>
    <fullName>Eye_Lens_Right__c</fullName>
    <inlineHelpText>Хрусталик правого глаза</inlineHelpText>
    <label>Eye Lens Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eye_Position_Left__c.field-meta.xml
<CustomField>
    <fullName>Eye_Position_Left__c</fullName>
    <inlineHelpText>Положение левого глаза - статус</inlineHelpText>
    <label>Eye Position Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eye_Position_Right__c.field-meta.xml
<CustomField>
    <fullName>Eye_Position_Right__c</fullName>
    <inlineHelpText>Положение правого глаза - статус</inlineHelpText>
    <label>Eye Position Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eyeground_Left__c.field-meta.xml
<CustomField>
    <fullName>Eyeground_Left__c</fullName>
    <inlineHelpText>Глазное дно левый глаз</inlineHelpText>
    <label>Eyeground Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eyeground_Right__c.field-meta.xml
<CustomField>
    <fullName>Eyeground_Right__c</fullName>
    <inlineHelpText>Глазное дно правый глаз</inlineHelpText>
    <label>Eyeground Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eyelid_Left__c.field-meta.xml
<CustomField>
    <fullName>Eyelid_Left__c</fullName>
    <description>{Id;Id}</description>
    <inlineHelpText>Веко левого глаза - статус.</inlineHelpText>
    <label>Eyelid Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Eyelid_Right__c.field-meta.xml
<CustomField>
    <fullName>Eyelid_Right__c</fullName>
    <description>{Id;Id}</description>
    <inlineHelpText>Веко правого глаза - статус</inlineHelpText>
    <label>Eyelid Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Inner_Eye_Pressure_Left__c.field-meta.xml
<CustomField>
    <fullName>Inner_Eye_Pressure_Left__c</fullName>
    <inlineHelpText>ВГД левый глаз. Пример: 15</inlineHelpText>
    <label>Inner Eye Pressure Left</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Inner_Eye_Pressure_Right__c.field-meta.xml
<CustomField>
    <fullName>Inner_Eye_Pressure_Right__c</fullName>
    <inlineHelpText>ВГД правый глаз. Пример:15</inlineHelpText>
    <label>Inner Eye Pressure Right</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Iris_Left__c.field-meta.xml
<CustomField>
    <fullName>Iris_Left__c</fullName>
    <inlineHelpText>Радужка,зрачок левый глаз</inlineHelpText>
    <label>Iris Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Iris_Right__c.field-meta.xml
<CustomField>
    <fullName>Iris_Right__c</fullName>
    <inlineHelpText>Роговица, зрачок правый глаз</inlineHelpText>
    <label>Iris Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Sphere_Left_Cor__c.field-meta.xml
<CustomField>
    <fullName>Sphere_Left_Cor__c</fullName>
    <inlineHelpText>Значение сферы с коррекцией, левый глаз. Пример: +1,25</inlineHelpText>
    <label>Sphere Left (Cor)</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Sphere_Right_Cor__c.field-meta.xml
<CustomField>
    <fullName>Sphere_Right_Cor__c</fullName>
    <inlineHelpText>Значение сферы правого глаза с коррекцией. Пример: +1,25</inlineHelpText>
    <label>Sphere Right (Cor)</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Visus_Left_Cor__c.field-meta.xml
<CustomField>
    <fullName>Visus_Left_Cor__c</fullName>
    <inlineHelpText>Визус после коррекции левый глаз</inlineHelpText>
    <label>Visus Left (Cor)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Visus_values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Visus_Left_Eye__c.field-meta.xml
<CustomField>
    <fullName>Visus_Left_Eye__c</fullName>
    <label>Visus Left Eye</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Visus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Visus_Right_Cor__c.field-meta.xml
<CustomField>
    <fullName>Visus_Right_Cor__c</fullName>
    <label>Visus Right (Cor)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Visus_values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Visus_Right_Eye__c.field-meta.xml
<CustomField>
    <fullName>Visus_Right_Eye__c</fullName>
    <label>Visus Right Eye</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Visus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Vitreous_Left__c.field-meta.xml
<CustomField>
    <fullName>Vitreous_Left__c</fullName>
    <inlineHelpText>Стекловидное тело левый глаз</inlineHelpText>
    <label>Vitreous Left</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objective_status__c/fields/Vitreous_Right__c.field-meta.xml
<CustomField>
    <fullName>Vitreous_Right__c</fullName>
    <inlineHelpText>Стекловидное тело правый глаз</inlineHelpText>
    <label>Vitreous Right</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ObjectiveInvestigationController.cls
/**
 * Created by IgorPekarskij on 05.01.2020.
 */

public with sharing class ObjectiveInvestigationController {

    @AuraEnabled
    public static LightningResponse getInitData(String objectiveStatusId) {
        LightningResponse response = new LightningResponse();
        Map<String, Object> responseMap = new Map<String, Object>();
        try{
            List<Objective_status__c> objectiveStatuses = [
                    SELECT
                            Anterior_Chamber_Angle_Left__c,
                            Anterior_Chamber_Angle_Right__c,
                            Anterior_Chamber_Left__c,
                            Anterior_Chamber_Right__c,
                            Anterior_Posterior_Axis_Left__c,
                            Anterior_Posterior_Axis_Right__c,
                            Axys_Left_Cor__c,
                            Axys_Right_Cor__c,
                            Central_Corneal_Thickness_Left__c,
                            Central_Corneal_Thickness_Right__c,
                            Conjunctiva_Left__c,
                            Conjunctiva_Right__c,
                            Cornea_Left__c,
                            Cornea_Right__c,
                            Cylinder_Left_Cor__c,
                            Cylinder_Right_Cor__c,
                            Eye_Lens_Left__c,
                            Eye_Lens_Right__c,
                            Eye_Position_Left__c,
                            Eye_Position_Right__c,
                            Eyeground_Left__c,
                            Eyeground_Right__c,
                            Eyelid_Left__c,
                            Eyelid_Right__c,
                            Inner_Eye_Pressure_Left__c,
                            Inner_Eye_Pressure_Right__c,
                            Iris_Left__c,
                            Iris_Right__c,
                            Sphere_Left_Cor__c,
                            Sphere_Right_Cor__c,
                            Visus_Left_Cor__c,
                            Visus_Left_Eye__c,
                            Visus_Right_Cor__c,
                            Visus_Right_Eye__c,
                            Vitreous_Left__c,
                            Vitreous_Right__c
                    FROM Objective_status__c WHERE Id =: objectiveStatusId
            ];
            responseMap.put('visus_left_eye__c', getPicklistOptions('Objective_status__c', 'Visus_Left_Eye__c'));
            responseMap.put('visus_left_cor__c', getPicklistOptions('Objective_status__c', 'Visus_Left_Cor__c'));
            if (objectiveStatuses.size() > 0) {
                responseMap.put('record', cloneExistingRecord(objectiveStatuses[0]));
            }
            response.setBody(responseMap);
        } catch (Exception e) {
            response.setError('Ошибка инициализации: ' + e.getMessage());
            System.debug('Ошибка инициализации \n ' + e.getMessage() + '\n' + e.getStackTraceString());
        }
        return response;
    }

    private static Objective_status__c cloneExistingRecord(Objective_status__c record) {
        Objective_status__c newRecord = record.clone(false, true);
        return newRecord;
    }


    private static List<Option> getPicklistOptions (String sObjectAPIName, String fieldAPIName) {
        List<Option> options = new List<Option>();
        if (Utility.GLOBAL_DESCRIBE_MAP.containsKey(sObjectAPIName)) {
            Map<String, SObjectField> fields = Utility.GLOBAL_DESCRIBE_MAP.get(sObjectAPIName).getDescribe().fields.getMap();
            if (fields.containsKey(fieldAPIName) && fields.get(fieldAPIName).getDescribe().getType() == DisplayType.PICKLIST) {
                for (Schema.PicklistEntry entry: fields.get(fieldAPIName).getDescribe().getPicklistValues()) {
                    options.add(new Option(entry.value, entry.label));
                }
            }
        }
        return options;
    }

    public class Option {
        @AuraEnabled public String value;
        @AuraEnabled public String label;

        public Option(String value, String label){
            this.value = value;
            this.label = label;
        }
    }
}